-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module RMWC.Classes.CircularProgress (rmwc_circular_progress, rmwc_circular_progress____indeterminate, rmwc_circular_progress____size_large, rmwc_circular_progress____size_medium, rmwc_circular_progress____size_small, rmwc_circular_progress____size_xlarge, rmwc_circular_progress____size_xsmall, rmwc_circular_progress____thickerstroke, rmwc_circular_progress__circle, rmwc_circular_progress__path, rmwc_icon) where

import Halogen.HTML (ClassName(..))

rmwc_circular_progress :: ClassName
rmwc_circular_progress = ClassName "rmwc-circular-progress"

rmwc_circular_progress____indeterminate :: ClassName
rmwc_circular_progress____indeterminate = ClassName "rmwc-circular-progress--indeterminate"

rmwc_circular_progress____size_large :: ClassName
rmwc_circular_progress____size_large = ClassName "rmwc-circular-progress--size-large"

rmwc_circular_progress____size_medium :: ClassName
rmwc_circular_progress____size_medium = ClassName "rmwc-circular-progress--size-medium"

rmwc_circular_progress____size_small :: ClassName
rmwc_circular_progress____size_small = ClassName "rmwc-circular-progress--size-small"

rmwc_circular_progress____size_xlarge :: ClassName
rmwc_circular_progress____size_xlarge = ClassName "rmwc-circular-progress--size-xlarge"

rmwc_circular_progress____size_xsmall :: ClassName
rmwc_circular_progress____size_xsmall = ClassName "rmwc-circular-progress--size-xsmall"

rmwc_circular_progress____thickerstroke :: ClassName
rmwc_circular_progress____thickerstroke = ClassName "rmwc-circular-progress--thickerstroke"

rmwc_circular_progress__circle :: ClassName
rmwc_circular_progress__circle = ClassName "rmwc-circular-progress__circle"

rmwc_circular_progress__path :: ClassName
rmwc_circular_progress__path = ClassName "rmwc-circular-progress__path"

rmwc_icon :: ClassName
rmwc_icon = ClassName "rmwc-icon"

