-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module RMWC.Classes.DataTable (mdc_data_table__row____selected, mdc_line_ripple, mdc_radio, mdc_select, mdc_select__anchor, mdc_select__native_control, mdc_switch, rmwc_data_table____sticky_columns_1, rmwc_data_table____sticky_rows_1, rmwc_data_table__cell, rmwc_data_table__cell____align_end, rmwc_data_table__cell____align_middle, rmwc_data_table__cell____align_start, rmwc_data_table__head, rmwc_data_table__head_cell____sortable, rmwc_data_table__head_cell____sortable_hover, rmwc_data_table__head_cell____sorted, rmwc_data_table__head_cell____sorted_ascending, rmwc_data_table__head_cell____sorted_descending, rmwc_data_table__row, rmwc_data_table__row____activated, rmwc_data_table__row____selected, rmwc_data_table__sort_icon) where

import Halogen.HTML (ClassName(..))

mdc_data_table__row____selected :: ClassName
mdc_data_table__row____selected = ClassName "mdc-data-table__row--selected"

mdc_line_ripple :: ClassName
mdc_line_ripple = ClassName "mdc-line-ripple"

mdc_radio :: ClassName
mdc_radio = ClassName "mdc-radio"

mdc_select :: ClassName
mdc_select = ClassName "mdc-select"

mdc_select__anchor :: ClassName
mdc_select__anchor = ClassName "mdc-select__anchor"

mdc_select__native_control :: ClassName
mdc_select__native_control = ClassName "mdc-select__native-control"

mdc_switch :: ClassName
mdc_switch = ClassName "mdc-switch"

rmwc_data_table____sticky_columns_1 :: ClassName
rmwc_data_table____sticky_columns_1 = ClassName "rmwc-data-table--sticky-columns-1"

rmwc_data_table____sticky_rows_1 :: ClassName
rmwc_data_table____sticky_rows_1 = ClassName "rmwc-data-table--sticky-rows-1"

rmwc_data_table__cell :: ClassName
rmwc_data_table__cell = ClassName "rmwc-data-table__cell"

rmwc_data_table__cell____align_end :: ClassName
rmwc_data_table__cell____align_end = ClassName "rmwc-data-table__cell--align-end"

rmwc_data_table__cell____align_middle :: ClassName
rmwc_data_table__cell____align_middle = ClassName "rmwc-data-table__cell--align-middle"

rmwc_data_table__cell____align_start :: ClassName
rmwc_data_table__cell____align_start = ClassName "rmwc-data-table__cell--align-start"

rmwc_data_table__head :: ClassName
rmwc_data_table__head = ClassName "rmwc-data-table__head"

rmwc_data_table__head_cell____sortable :: ClassName
rmwc_data_table__head_cell____sortable = ClassName "rmwc-data-table__head-cell--sortable"

rmwc_data_table__head_cell____sortable_hover :: ClassName
rmwc_data_table__head_cell____sortable_hover = ClassName "rmwc-data-table__head-cell--sortable-hover"

rmwc_data_table__head_cell____sorted :: ClassName
rmwc_data_table__head_cell____sorted = ClassName "rmwc-data-table__head-cell--sorted"

rmwc_data_table__head_cell____sorted_ascending :: ClassName
rmwc_data_table__head_cell____sorted_ascending = ClassName "rmwc-data-table__head-cell--sorted-ascending"

rmwc_data_table__head_cell____sorted_descending :: ClassName
rmwc_data_table__head_cell____sorted_descending = ClassName "rmwc-data-table__head-cell--sorted-descending"

rmwc_data_table__row :: ClassName
rmwc_data_table__row = ClassName "rmwc-data-table__row"

rmwc_data_table__row____activated :: ClassName
rmwc_data_table__row____activated = ClassName "rmwc-data-table__row--activated"

rmwc_data_table__row____selected :: ClassName
rmwc_data_table__row____selected = ClassName "rmwc-data-table__row--selected"

rmwc_data_table__sort_icon :: ClassName
rmwc_data_table__sort_icon = ClassName "rmwc-data-table__sort-icon"

