-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module RMWC.Classes.Select (mdc_select__anchor, rmwc_select__native_control) where

import Halogen.HTML (ClassName(..))

mdc_select__anchor :: ClassName
mdc_select__anchor = ClassName "mdc-select__anchor"

rmwc_select__native_control :: ClassName
rmwc_select__native_control = ClassName "rmwc-select__native-control"

