-- Do not edit, this file was autogenerated by generate-halogen-css-modules
module NextjsApp.PageImplementations.VerifyUserEmailMobile.Css (styles) where

import Halogen.HTML (ClassName)

foreign import styles ::
  { root :: ClassName
  }
