#!/bin/sh -e

# idea stolen from https://gist.github.com/nicerobot/1136dcfba6ce3da67ce3ded5101a4078

# USAGE
# ./wait-for-postgres postgres://$LOGIN:$PASSWORD@$HOST:$PORT/$DATABASE

# Retries a command on failure (idea stolen from http://fahdshariff.blogspot.com/2014/02/retrying-commands-in-shell-scripts.html).
# $1 - the max number of attempts
# $2 - the seconds to sleep
# $3... - the command to run
retry() {
  max_attempts="$1"; shift
  seconds="$1"; shift
  cmd="$@"
  attempt_num=1

  until $cmd
  do
    if [ $attempt_num -eq $max_attempts ]
    then
      echo "Attempt $attempt_num failed and there are no more attempts left!"
      return 1
    else
      echo "Attempt $attempt_num failed! Trying again in $seconds seconds..."
      attempt_num=`expr "$attempt_num" + 1`
      sleep "$seconds"
    fi
  done
}

retry 5 1 psql -c '\l' ${@} >/dev/null

echo >&2 "$(date +%Y%m%dt%H%M%S) Postgres is up - executing command"
