module Worker.JobIds where

-- generated by ./gen-job-ids-from-migrations.hs

type JobIds a =
  { "JOB__SEND_PASSWORD_CHANGED_EMAIL" :: a
  , "JOB__SEND_PASSWORD_RESET_EMAIL" :: a
  , "JOB__SEND_VERIFICATION_EMAIL_FOR_USER_EMAIL" :: a
  }
