-- Do not edit, this file was autogenerated by generate-halogen-css-modules
module Nextjs.PageImplementations.Login.Css (styles) where

import Halogen.HTML (ClassName)

foreign import styles ::
  { root :: ClassName
  , logo :: ClassName
  , buttons :: ClassName
  }
