-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.FormField (mdc_form_field, mdc_form_field____align_end) where

import Halogen.HTML (ClassName(..))

mdc_form_field :: ClassName
mdc_form_field = ClassName "mdc-form-field"

mdc_form_field____align_end :: ClassName
mdc_form_field____align_end = ClassName "mdc-form-field--align-end"

