-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.GridList (mdc_grid_list, mdc_grid_list____header_caption, mdc_grid_list____tile_aspect_16x9, mdc_grid_list____tile_aspect_2x3, mdc_grid_list____tile_aspect_3x2, mdc_grid_list____tile_aspect_3x4, mdc_grid_list____tile_aspect_4x3, mdc_grid_list____tile_gutter_1, mdc_grid_list____twoline_caption, mdc_grid_list____with_icon_align_end, mdc_grid_list____with_icon_align_start, mdc_grid_list__tiles, mdc_grid_tile, mdc_grid_tile__icon, mdc_grid_tile__primary, mdc_grid_tile__primary_content, mdc_grid_tile__secondary, mdc_grid_tile__support_text, mdc_grid_tile__title) where

import Halogen.HTML (ClassName(..))

mdc_grid_list :: ClassName
mdc_grid_list = ClassName "mdc-grid-list"

mdc_grid_list____header_caption :: ClassName
mdc_grid_list____header_caption = ClassName "mdc-grid-list--header-caption"

mdc_grid_list____tile_aspect_16x9 :: ClassName
mdc_grid_list____tile_aspect_16x9 = ClassName "mdc-grid-list--tile-aspect-16x9"

mdc_grid_list____tile_aspect_2x3 :: ClassName
mdc_grid_list____tile_aspect_2x3 = ClassName "mdc-grid-list--tile-aspect-2x3"

mdc_grid_list____tile_aspect_3x2 :: ClassName
mdc_grid_list____tile_aspect_3x2 = ClassName "mdc-grid-list--tile-aspect-3x2"

mdc_grid_list____tile_aspect_3x4 :: ClassName
mdc_grid_list____tile_aspect_3x4 = ClassName "mdc-grid-list--tile-aspect-3x4"

mdc_grid_list____tile_aspect_4x3 :: ClassName
mdc_grid_list____tile_aspect_4x3 = ClassName "mdc-grid-list--tile-aspect-4x3"

mdc_grid_list____tile_gutter_1 :: ClassName
mdc_grid_list____tile_gutter_1 = ClassName "mdc-grid-list--tile-gutter-1"

mdc_grid_list____twoline_caption :: ClassName
mdc_grid_list____twoline_caption = ClassName "mdc-grid-list--twoline-caption"

mdc_grid_list____with_icon_align_end :: ClassName
mdc_grid_list____with_icon_align_end = ClassName "mdc-grid-list--with-icon-align-end"

mdc_grid_list____with_icon_align_start :: ClassName
mdc_grid_list____with_icon_align_start = ClassName "mdc-grid-list--with-icon-align-start"

mdc_grid_list__tiles :: ClassName
mdc_grid_list__tiles = ClassName "mdc-grid-list__tiles"

mdc_grid_tile :: ClassName
mdc_grid_tile = ClassName "mdc-grid-tile"

mdc_grid_tile__icon :: ClassName
mdc_grid_tile__icon = ClassName "mdc-grid-tile__icon"

mdc_grid_tile__primary :: ClassName
mdc_grid_tile__primary = ClassName "mdc-grid-tile__primary"

mdc_grid_tile__primary_content :: ClassName
mdc_grid_tile__primary_content = ClassName "mdc-grid-tile__primary-content"

mdc_grid_tile__secondary :: ClassName
mdc_grid_tile__secondary = ClassName "mdc-grid-tile__secondary"

mdc_grid_tile__support_text :: ClassName
mdc_grid_tile__support_text = ClassName "mdc-grid-tile__support-text"

mdc_grid_tile__title :: ClassName
mdc_grid_tile__title = ClassName "mdc-grid-tile__title"

