-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.LayoutGrid (mdc_layout_grid) where

import Halogen.HTML (ClassName(..))

mdc_layout_grid :: ClassName
mdc_layout_grid = ClassName "mdc-layout-grid"

