-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.TabBar (mdc_tab, mdc_tab____stacked, mdc_tab_bar) where

import Halogen.HTML (ClassName(..))

mdc_tab :: ClassName
mdc_tab = ClassName "mdc-tab"

mdc_tab____stacked :: ClassName
mdc_tab____stacked = ClassName "mdc-tab--stacked"

mdc_tab_bar :: ClassName
mdc_tab_bar = ClassName "mdc-tab-bar"

