-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.Theme (mdc_theme____background, mdc_theme____error, mdc_theme____on_error, mdc_theme____on_primary, mdc_theme____on_secondary, mdc_theme____on_surface, mdc_theme____primary, mdc_theme____primary_bg, mdc_theme____secondary, mdc_theme____secondary_bg, mdc_theme____surface, mdc_theme____text_disabled_on_background, mdc_theme____text_disabled_on_dark, mdc_theme____text_disabled_on_light, mdc_theme____text_hint_on_background, mdc_theme____text_hint_on_dark, mdc_theme____text_hint_on_light, mdc_theme____text_icon_on_background, mdc_theme____text_icon_on_dark, mdc_theme____text_icon_on_light, mdc_theme____text_primary_on_background, mdc_theme____text_primary_on_dark, mdc_theme____text_primary_on_light, mdc_theme____text_secondary_on_background, mdc_theme____text_secondary_on_dark, mdc_theme____text_secondary_on_light) where

import Halogen.HTML (ClassName(..))

mdc_theme____background :: ClassName
mdc_theme____background = ClassName "mdc-theme--background"

mdc_theme____error :: ClassName
mdc_theme____error = ClassName "mdc-theme--error"

mdc_theme____on_error :: ClassName
mdc_theme____on_error = ClassName "mdc-theme--on-error"

mdc_theme____on_primary :: ClassName
mdc_theme____on_primary = ClassName "mdc-theme--on-primary"

mdc_theme____on_secondary :: ClassName
mdc_theme____on_secondary = ClassName "mdc-theme--on-secondary"

mdc_theme____on_surface :: ClassName
mdc_theme____on_surface = ClassName "mdc-theme--on-surface"

mdc_theme____primary :: ClassName
mdc_theme____primary = ClassName "mdc-theme--primary"

mdc_theme____primary_bg :: ClassName
mdc_theme____primary_bg = ClassName "mdc-theme--primary-bg"

mdc_theme____secondary :: ClassName
mdc_theme____secondary = ClassName "mdc-theme--secondary"

mdc_theme____secondary_bg :: ClassName
mdc_theme____secondary_bg = ClassName "mdc-theme--secondary-bg"

mdc_theme____surface :: ClassName
mdc_theme____surface = ClassName "mdc-theme--surface"

mdc_theme____text_disabled_on_background :: ClassName
mdc_theme____text_disabled_on_background = ClassName "mdc-theme--text-disabled-on-background"

mdc_theme____text_disabled_on_dark :: ClassName
mdc_theme____text_disabled_on_dark = ClassName "mdc-theme--text-disabled-on-dark"

mdc_theme____text_disabled_on_light :: ClassName
mdc_theme____text_disabled_on_light = ClassName "mdc-theme--text-disabled-on-light"

mdc_theme____text_hint_on_background :: ClassName
mdc_theme____text_hint_on_background = ClassName "mdc-theme--text-hint-on-background"

mdc_theme____text_hint_on_dark :: ClassName
mdc_theme____text_hint_on_dark = ClassName "mdc-theme--text-hint-on-dark"

mdc_theme____text_hint_on_light :: ClassName
mdc_theme____text_hint_on_light = ClassName "mdc-theme--text-hint-on-light"

mdc_theme____text_icon_on_background :: ClassName
mdc_theme____text_icon_on_background = ClassName "mdc-theme--text-icon-on-background"

mdc_theme____text_icon_on_dark :: ClassName
mdc_theme____text_icon_on_dark = ClassName "mdc-theme--text-icon-on-dark"

mdc_theme____text_icon_on_light :: ClassName
mdc_theme____text_icon_on_light = ClassName "mdc-theme--text-icon-on-light"

mdc_theme____text_primary_on_background :: ClassName
mdc_theme____text_primary_on_background = ClassName "mdc-theme--text-primary-on-background"

mdc_theme____text_primary_on_dark :: ClassName
mdc_theme____text_primary_on_dark = ClassName "mdc-theme--text-primary-on-dark"

mdc_theme____text_primary_on_light :: ClassName
mdc_theme____text_primary_on_light = ClassName "mdc-theme--text-primary-on-light"

mdc_theme____text_secondary_on_background :: ClassName
mdc_theme____text_secondary_on_background = ClassName "mdc-theme--text-secondary-on-background"

mdc_theme____text_secondary_on_dark :: ClassName
mdc_theme____text_secondary_on_dark = ClassName "mdc-theme--text-secondary-on-dark"

mdc_theme____text_secondary_on_light :: ClassName
mdc_theme____text_secondary_on_light = ClassName "mdc-theme--text-secondary-on-light"

